# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kaoshenghao', models.CharField(blank=True, max_length=150, null=True)),
                ('shenfenzhenghao', models.CharField(blank=True, max_length=150, null=True)),
                ('xingming', models.CharField(blank=True, max_length=150, null=True)),
                ('xingbiedaima', models.CharField(blank=True, max_length=150, null=True)),
                ('xingbie', models.CharField(blank=True, max_length=150, null=True)),
                ('minzudaima', models.CharField(blank=True, max_length=150, null=True)),
                ('minzu', models.CharField(blank=True, max_length=150, null=True)),
                ('zhengzhimianmaodaima', models.CharField(blank=True, max_length=150, null=True)),
                ('zhengzhimianmao', models.CharField(blank=True, max_length=150, null=True)),
                ('yuanxiaodaima', models.CharField(blank=True, max_length=150, null=True)),
                ('yuanxiaomingcheng', models.CharField(blank=True, max_length=150, null=True)),
                ('fenxiaomingcheng', models.CharField(blank=True, max_length=150, null=True)),
                ('xuelidaima', models.CharField(blank=True, max_length=150, null=True)),
                ('xueli', models.CharField(blank=True, max_length=150, null=True)),
                ('zhuanyedaima', models.CharField(blank=True, max_length=150, null=True)),
                ('zhuanye', models.CharField(blank=True, max_length=150, null=True)),
                ('zhuanyefangxiang', models.CharField(blank=True, max_length=150, null=True)),
                ('peiyangfangshidaima', models.CharField(blank=True, max_length=150, null=True)),
                ('peiyangfangshi', models.CharField(blank=True, max_length=150, null=True)),
                ('dingxianghuoweipeidanwei', models.CharField(blank=True, max_length=150, null=True)),
                ('shengyuansuozaididaima', models.CharField(blank=True, max_length=150, null=True)),
                ('shengyuansuozaidi', models.CharField(blank=True, max_length=150, null=True)),
                ('chengxiangshengyuan', models.CharField(blank=True, max_length=150, null=True)),
                ('xuezhi', models.CharField(blank=True, max_length=150, null=True)),
                ('ruxueshijian', models.CharField(blank=True, max_length=150, null=True)),
                ('biyeshijian', models.CharField(blank=True, max_length=150, null=True)),
                ('shifanshengleibiedaima', models.CharField(blank=True, max_length=150, null=True)),
                ('shifanshengleibie', models.CharField(blank=True, max_length=150, null=True)),
                ('kunnanshengleibiedaima', models.CharField(blank=True, max_length=150, null=True)),
                ('kunnanshengleibie', models.CharField(blank=True, max_length=150, null=True)),
                ('suozaiyuanxi', models.CharField(blank=True, max_length=150, null=True)),
                ('suozaibanji', models.CharField(blank=True, max_length=150, null=True)),
                ('xuehao', models.CharField(blank=True, max_length=150, null=True)),
                ('chushengriqi', models.CharField(blank=True, max_length=150, null=True)),
                ('shoujihaoma', models.CharField(blank=True, max_length=150, null=True)),
                ('biyequxiangdaima', models.CharField(blank=True, max_length=150, null=True)),
                ('biyequxiang', models.CharField(blank=True, max_length=150, null=True)),
                ('danweizuzhijigoudaima', models.CharField(blank=True, max_length=150, null=True)),
                ('danweimingcheng', models.CharField(blank=True, max_length=150, null=True)),
                ('danweixingzhidaima', models.CharField(blank=True, max_length=150, null=True)),
                ('danweixingzhi', models.CharField(blank=True, max_length=150, null=True)),
                ('danweihangyedaima', models.CharField(blank=True, max_length=150, null=True)),
                ('danweihangye', models.CharField(blank=True, max_length=150, null=True)),
                ('danweisuozaididaima', models.CharField(blank=True, max_length=150, null=True)),
                ('danweisuozaidi', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
